### ISSUE TITLE
회원 등급제 적용

### ISSUE THREAD

**Issue by Imseo-Platform** [Imseo-Platform/issuetracker#2]
https://platformimseo.slack.com/archives/G01L6N3EA31/p1612880046004800
- 업로드 가능한 회원과 불가능한 회원 분류
- 등급 별로 볼수있는 아이콘 분류 적용

**Comment by kimdh7** [comment]
https://github.com/DavidJeon77/rt_gram/pull/4/commits/5786ff88abde1c275c3dc1d4365d585c7859f531 적용완료
